name: Java CI with Maven

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: 11
    - name: Clone
      run: git clone --depth=1 https://LorenzoBettini:${{ secrets.GITHUB_TOKEN }}@github.com/LorenzoBettini/p2composite-github-pages-example-updates
    - name: Tree
      run: tree
    - name: Modify a file
      run: date +%s > p2composite-github-pages-example-updates/report.txt
    - name: Commit
      run: |
        git config --global user.name 'LorenzoBettini'
        git config --global user.email 'lorenzo.bettini@users.noreply.github.com'
        git -C p2composite-github-pages-example-updates add -A
        git -C p2composite-github-pages-example-updates commit -am "Automated report"
        git -C p2composite-github-pages-example-updates push
